const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USER: 'GET_ALL_USER',
    GET_ALL_CATEGORY: 'GET_ALL_CATEGORY',
    GET_ALL_IDEA_STAFF: 'GET_ALL_IDEA_STAFF',
    GET_IDEA: 'GET_IDEA',
    SORT_IDEA: 'SORT_IDEA',
    IDEALL_STAFF: 'IDEALL_STAFF',
    DASH_BOARD: 'DASH_BOARD',
    GET_ALL_DEPARTMENT: 'GET_ALL_DEPARTMENT',
    GET_ONE_DEPARTMENT: 'GET_ONE_DEPARTMENT',
    GET_AVATAR: 'GET_AVATAR',
}
export default ACTIONS